# Bare kjøre på hovedbranch
if: branch = master

language: node_js
node_js: '10'
cache:
  - yarn

install:
- yarn install --non-interactive --pure-lockfile

before_script:
- yarn run lint

script:
- CI=false yarn run build || travis_terminate 1;

# after_script:
#- firebase deploy -m "Travis, Build $TRAVIS_BUILD_NUMBER, commit $TRAVIS_COMMIT" --non-interactive --token $FIREBASE_TOKEN